// let = a,b,c;

// try {
//     console.log("try frist")
//     let =3/a

// } catch (error) {
//     console.log("error name",error.name)
//      console.log("error message",error.message)
// }finally{
//     console.log("end")
// }
let b;
let a;
try {
    console.log("hai")
    b=two()
    a=fuone()
} catch (er) {
b=20
a=40
    
}finally{
    console.log("end")
}



let c=fufinal(a,b)
console.log(c)
function fuone(){
    dsfsd()
    return 10
}
function two(){
    fj()
    return 10
}
function fufinal(a,b){
    return a+b
}